### ISSUE TITLE
How to convert Mainnet to Testnet in ether?

### ISSUE THREAD

**Issue by sazzad7002** [ethers-io/ethers.objc#14]
Account *account = [Account accountWithMnemonicPhrase:mnemonicPhrase];
Address *address = account.address;

API URL: "api.etherscan.io"

For, Getting all value means gasPrice, estimate gas. 
please provide proper solution.

**Comment by ricmoo** [comment]
To get query the network, you should look at the Provider API. For example:

```
Provider *provider = [[InfuraProvider alloc] initWithChainId:chainId];
```
