### ISSUE TITLE
Mnemonic path modification

### ISSUE THREAD

**Issue by SkyByte93** [ethers-io/ethers.objc#22]
What is the path when importing mnemonic?

**Comment by ricmoo** [comment]
The default path for ETH is `m/44'/60'/0'/0/0`, for account #0.

The default path for ETH is `m/44'/60'/1'/0/0`, for account #1.

And so on. For more information, check out [BIP 44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)

Let me know if you have any more questions. The last two parts of the path don't have a lot of meaning in the context of Ethereum, and should just be `/0/0`, and are mostly for Bitcoin necessities...

**Comment by ricmoo** [comment]
Closing this, but if you have any more questions, please feel free to re-open. :)
