### ISSUE TITLE
Create ethereum wallet

### ISSUE THREAD

**Issue by acroix** [ethers-io/ethers.objc#5]
Hi,

Great work here. I am not an Objective C developper but I have to create a Light etherum wallet and I don't really know where to start. 
I have a react-native app with a register form and need to create a wallet for this user. I don't know which class I should use: Account ? Provider ?

Thanks for your help and time

**Comment by ricmoo** [comment]
You likely need both of those.

Provider connects to the blockchain, while Account manages the private key needed to sign transactions.

I recommend trying out a few simple transactions on testnet first to get an idea of how things work. It might also help to try out ethers.js in a node REPL shell too. There are lots of complexities and security issues to get used to before you jump in and write a wallet.
